### ISSUE TITLE
a way to set a new min and/or max val

### ISSUE THREAD

**Issue by sebasdt** [gfvalvo/NewEncoder#12]
is there a function that could set a new min value or max value?
or can it only be done when the encoder is "created"?

**Comment by gfvalvo** [comment]
Use end() followed by configure() and begin(). These functions are described in the ReadMe.

**Comment by sebasdt** [comment]
thanks! didn't think of doing it that way.

**Comment by gfvalvo** [comment]
Just added a simpler way. See the newSettings() in the ReadME.
