### ISSUE TITLE
trying to use the value on switch... case

### ISSUE THREAD

**Issue by andrefcarvalho** [gfvalvo/NewEncoder#14]
I'm using a scale as an example from 1 to 5, and then use it with switch... in case, by serial I confirm the value, but in the switch... in case it doesn't assume the same, any solution?

**Comment by gfvalvo** [comment]
Your problem statement is unclear. Please post the code you're having a problem with. Clearing explain how it is not behaving as you expected.

**Comment by gfvalvo** [comment]
Receiving no clarification of the problem @andrefcarvalho is having, I'm closing this issue.
