### ISSUE TITLE
would your code work on arduino Unos with unsigned long as counter-variable?

### ISSUE THREAD

**Issue by StefanL38** [gfvalvo/NewEncoder#17]
Hi gfvavlo,

I have a question:

would your NewEncoder-library work with a pulse-counter variable of type unsigned long?
or would the non atomic access to an unsigned long cause unreliable counting of the pulses?

**Comment by gfvalvo** [comment]
Atomic access isn't the issue. The relevant class member variables are all of type 'int16_t'. It could be rewritten to use a different type. Or, perhaps, even templated to all the user to select the type at compile-time. You can certainly fork the library and do that. If you do, post a Pull Request and I'll consider incorporating your modifications.
