### ISSUE TITLE
can't compile

### ISSUE THREAD

**Issue by thijsdeschildre** [gfvalvo/NewEncoder#2]
Two issues when trying to compile the example:
first, I need to add this to interrupt_pins.h:

#ifdef __cplusplus
extern` "C" {
#endif`

otherwise I get the errors
`C:\Users\Thijs\AppData\Local\Temp\ccKb6QYd.ltrans0.ltrans.o: In function `main':
C:\Users\Thijs\AppData\Local\Arduino15\packages\ATTinyCore\hardware\avr\1.3.2\cores\tiny/main.cpp:10: undefined reference to `setup'
C:\Users\Thijs\AppData\Local\Temp\ccKb6QYd.ltrans0.ltrans.o: In function `__static_initialization_and_destruction_0':
C:\SingleEncoder/SingleEncoder.ino:13: undefined reference to `NewEncoder::NewEncoder(unsigned char, unsigned char, int, int, int, unsigned char)'
C:\Users\Thijs\AppData\Local\Temp\ccKb6QYd.ltrans0.ltrans.o: In function `_GLOBAL__sub_D_encoder':
C:\SingleEncoder/SingleEncoder.ino:13: undefined reference to `NewEncoder::~NewEncoder()'
collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board ATtiny25/45/85.`

After that, I get these errors:

`
SingleEncoder:55:1: error: expected '}' at end of input
 }
 ^
exit status 1
expected '}' at end of input
`

I don't see a bracket missing in the example, so I don't really get what's going wrong.
I'm using arduino suite 1.8.11 on windows 10

**Comment by gfvalvo** [comment]
Code currently on GitHub compiles for all "Arduino" ecosystem boards that I've tried.
