### ISSUE TITLE
Raspberry Pico Arduino Support?

### ISSUE THREAD

**Issue by unreal4me** [gfvalvo/NewEncoder#30]
https://arduino-pico.readthedocs.io/en/latest/contrib.html#porting-libraries-and-applications-to-the-core

Hi there, 
Adding includes for RP2040 would be nice

**Comment by gfvalvo** [comment]
> Adding includes for RP2040 would be nice

I don't have an RP2040 to test. Please fork the library, modify and test the code, and then do a GitHub Pull Request. I'll be happy to integrate it.
