### ISSUE TITLE
No examples on how to use the getAndSet() function

### ISSUE THREAD

**Issue by F4ceMeltor** [gfvalvo/NewEncoder#32]
I tried to use the old setValue() func but it threw me an odd error "grpc: error while marshaling: string field contains invalid UTF-8". Googling around, people mentioned it might be related to the fact that my name contains such a letter, so I abandoned the deprecated function and tried to use the new one; however, I have no idea where I am supposed to get the &oldstate and &newstate from. I'm just trying to pass a number, I don't really know why these state things are necessary.

**Comment by F4ceMeltor** [comment]
I think I found another issue. Your old deprecated int16_t-only getAndSet() function is still present and named exactly the same as the new one.

**Comment by gfvalvo** [comment]
Regarding the duplicated function name, they have different signatures. So they are simply two overloads of the same function name and there's no conflict.

Regarding the "new" getAndSet(), `oldState` and `newState` are variables of type `NewEncoder::EncoderState` that you provide in the function call. The function atomically sets them as described in the [README](https://github.com/gfvalvo/NewEncoder/tree/master#get-current-encoder-state-and-change-value)
