### ISSUE TITLE
Slash problem in NewEncoder.h

### ISSUE THREAD

**Issue by golikp** [gfvalvo/NewEncoder#4]
A minor issue: when compiling on a Mac (I guess any *nix would be the same), I get
```
fatal error: utility\interrupt_pins.h: No such file or directory
 #include "utility\interrupt_pins.h"
```
It's enough to change backslashes to slashes in NewEncoder.h, and then it works. No idea, how to make this universal.

**Comment by gfvalvo** [comment]
Addressed in latest GitHub update.
