### ISSUE TITLE
NewEncoder not supported for ESP32?

### ISSUE THREAD

**Issue by sebasdt** [gfvalvo/NewEncoder#5]
thanks for writing this awesome library!
But a few days ago I replaced my ESP8266 to an ESP32 and unfortunately found out that it's not supported. Tried to update the library using the Arduino ide library searcher and it didn't have any. Since then I am trying to write the code needed to support the esp32. could you please update this or something else?

**Comment by sebasdt** [comment]
no one has answered. found another one that worked: AiEsp32RotaryEncoder.

**Comment by gfvalvo** [comment]
The latest version on GitHub now works with ESP32. Also see the new FreeRTOS example that's included.
