### ISSUE TITLE
pls add start stop encoder or enable disable

### ISSUE THREAD

**Issue by viorelbejan** [gfvalvo/NewEncoder#7]

**Comment by lukas0711** [comment]
Just use `encoder.end()` as described in the README.md:

Disable an encoder object
` void end();`
Arguments: None
Returns: Nothing

**Comment by gfvalvo** [comment]
> Just use `encoder.end()` as described in the README.md:
> 
> Disable an encoder object
> ` void end();`
> Arguments: None
> Returns: Nothing

Correct.
