### ISSUE TITLE
ESP8266 and ESP32 not supportet (ISR ICACHE_RAM_ATTR)

### ISSUE THREAD

**Issue by lukas0711** [gfvalvo/NewEncoder#8]
The ESP8266 and ESP32 need the function called in attatchInterrupt to be declared as an ICACHE_RAM_ATTR as explained here:
https://arduino-esp8266.readthedocs.io/en/latest/faq/a02-my-esp-crashes.html?highlight=ICACHE_RAM_ATTR#other-causes-for-crashes
Otherwise the ESP will crash.
#6 Adds support for these boards.

**Comment by gfvalvo** [comment]
Addressed.
